#spring:
#  application:
#    name: subcategory-service
#
server:
  port: 9008

spring:
  application:
    name: subcategory-service

  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12810248?createDatabaseIfNotExist=true
    username: sql12810248
    password: SqG5w4ebQ2
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
  #    username: root
  #    password: 1234
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:postgresql://localhost:5433/testing
  #    username: root
  #    password: root
  #    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


